import { DiffResult, DiffChange } from '../types';
import { diffLines, Change } from 'diff';
import JSZip from 'jszip';
import { jsPDF } from 'jspdf';
import { saveAs } from 'file-saver';
import html2canvas from 'html2canvas';

// 计算文件差异
export function calculateDiff(oldContent: string, newContent: string, filename: string): DiffResult {
  const changes = diffLines(oldContent, newContent);
  const diffChanges: DiffChange[] = [];
  let lineNumber = 1;
  let additions = 0;
  let deletions = 0;

  changes.forEach((change: Change) => {
    const lines = change.value.split('\n').filter(l => l !== '' || change.value === '\n');

    lines.forEach(line => {
      if (change.added) {
        diffChanges.push({ type: 'add', lineNumber, content: line });
        additions++;
      } else if (change.removed) {
        diffChanges.push({ type: 'remove', lineNumber, content: line });
        deletions++;
      } else {
        diffChanges.push({ type: 'unchanged', lineNumber, content: line });
      }
      lineNumber++;
    });
  });

  return {
    filename,
    oldContent,
    newContent,
    additions,
    deletions,
    changes: diffChanges
  };
}

// 导出为 ZIP 文件
export async function exportAsZip(
  files: { name: string; content: string }[],
  filename: string = 'project'
): Promise<void> {
  try {
    const zip = new JSZip();

    // 添加文件到ZIP
    files.forEach(file => {
      if (file.name && file.content) {
        zip.file(file.name, file.content);
      }
    });

    // 添加项目说明文件
    const readmeContent = `# ${filename}

Generated by AiCoder

## Files
${files.map(f => `- ${f.name}`).join('\n')}

---
Generated at: ${new Date().toLocaleString()}
`;
    zip.file('README.md', readmeContent);

    // 生成ZIP文件
    const blob = await zip.generateAsync({
      type: 'blob',
      compression: 'DEFLATE',
      compressionOptions: { level: 6 }
    });

    // 下载文件
    saveAs(blob, `${filename}.zip`);
  } catch (error) {
    console.error('ZIP导出失败:', error);
    throw new Error('ZIP导出失败，请稍后重试');
  }
}

// 导出为 PDF（修复乱码问题，优化显示效果）
export function exportAsPdf(
  content: string,
  title: string = '代码生成结果'
): void {
  try {
    const doc = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4'
    });

    // 设置页面边距
    const margin = 20;
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const contentWidth = pageWidth - margin * 2;

    // 标题
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text(title, margin, margin);

    // 分割内容为多行，处理代码块
    const lines = content.split('\n');
    let y = margin + 15;
    let lineHeight = 6;

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');

    for (let i = 0; i < lines.length; i++) {
      const line = lines[i];

      // 检测是否为代码块标记
      if (line.startsWith('```')) {
        // 跳过代码块标记
        continue;
      }

      // 检测是否为消息分隔符
      if (line.match(/^---+$/)) {
        doc.setDrawColor(200, 200, 200);
        doc.line(margin, y, pageWidth - margin, y);
        y += lineHeight;
        continue;
      }

      // 检测是否为角色标识
      if (line.startsWith('[') && line.includes(']')) {
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(59, 130, 246); // 蓝色
        const roleLines = doc.splitTextToSize(line, contentWidth);
        for (const roleLine of roleLines) {
          if (y > pageHeight - margin) {
            doc.addPage();
            y = margin;
          }
          doc.text(roleLine, margin, y);
          y += lineHeight;
        }
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(0, 0, 0);
        continue;
      }

      // 普通文本
      const isCodeLine = line.startsWith('//') || line.startsWith('#') ||
                         line.startsWith('import ') || line.startsWith('export ') ||
                         line.match(/^[a-zA-Z_$][\w$]*\s*=/);

      if (isCodeLine) {
        doc.setFont('courier', 'normal');
        doc.setFontSize(9);
        lineHeight = 5;
      } else {
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(10);
        lineHeight = 6;
      }

      const textLines = doc.splitTextToSize(line || ' ', contentWidth);

      for (const textLine of textLines) {
        if (y > pageHeight - margin) {
          doc.addPage();
          y = margin;
        }
        doc.text(textLine, margin, y);
        y += lineHeight;
      }
    }

    // 添加页码
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(128, 128, 128);
      doc.text(
        `第 ${i} 页 / 共 ${pageCount} 页`,
        pageWidth / 2,
        pageHeight - 10,
        { align: 'center' }
      );
    }

    // 保存PDF
    doc.save(`${title}.pdf`);
  } catch (error) {
    console.error('PDF导出失败:', error);
    throw new Error('PDF导出失败，请稍后重试');
  }
}

// 导出为图片（对话长图 - 截取整个滚动区域）
export async function exportConversationImage(
  element: HTMLElement,
  filename: string = 'conversation'
): Promise<void> {
  try {
    // 获取元素的完整高度（包括滚动内容）
    const scrollHeight = element.scrollHeight;
    const clientHeight = element.clientHeight;
    const actualHeight = Math.max(scrollHeight, clientHeight);

    // 创建临时容器用于截图
    const container = document.createElement('div');
    container.style.position = 'absolute';
    container.style.left = '-9999px';
    container.style.top = '0';
    container.style.width = element.offsetWidth + 'px';
    container.style.height = actualHeight + 'px';
    container.style.backgroundColor = '#111827'; // 对应 bg-gray-900
    document.body.appendChild(container);

    // 克隆元素
    const clone = element.cloneNode(true) as HTMLElement;
    clone.style.overflow = 'visible';
    clone.style.height = 'auto';
    container.appendChild(clone);

    // 等待DOM更新
    await new Promise(resolve => setTimeout(resolve, 200));

    // 使用html2canvas截图 - 截取完整高度
    const canvas = await html2canvas(clone, {
      backgroundColor: '#111827',
      scale: 2, // 提高清晰度
      useCORS: true,
      logging: false,
      width: element.offsetWidth,
      height: actualHeight,
      scrollY: 0,
      scrollX: 0,
      windowWidth: element.offsetWidth,
      windowHeight: actualHeight
    });

    // 移除临时容器
    document.body.removeChild(container);

    // 转换为图片并下载
    canvas.toBlob((blob) => {
      if (blob) {
        saveAs(blob, `${filename}.png`);
      }
    }, 'image/png');
  } catch (error) {
    console.error('图片导出失败:', error);
    throw new Error('图片导出失败，请稍后重试');
  }
}

// 复制到剪贴板
export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    // 降级方案
    const textarea = document.createElement('textarea');
    textarea.value = text;
    textarea.style.position = 'fixed';
    textarea.style.opacity = '0';
    document.body.appendChild(textarea);
    textarea.select();
    const success = document.execCommand('copy');
    document.body.removeChild(textarea);
    return success;
  }
}

// 格式化代码（简单格式化）
export function formatCode(code: string, language: string): string {
  // 根据语言进行基本格式化
  const lines = code.split('\n');
  let indentLevel = 0;
  const indentChar = '  ';

  const formatted = lines.map(line => {
    const trimmed = line.trim();

    // 减少缩进的字符
    if (/^[}\])]/.test(trimmed)) {
      indentLevel = Math.max(0, indentLevel - 1);
    }

    const result = indentChar.repeat(indentLevel) + trimmed;

    // 增加缩进的字符
    if (/[{(\[]$/.test(trimmed) && !trimmed.includes('//')) {
      indentLevel++;
    }

    return result;
  });

  return formatted.join('\n');
}

// 生成代码高亮 HTML
export function generateHighlightedHtml(code: string, language: string): string {
  // 简单的语法高亮
  const keywords: { [key: string]: string[] } = {
    javascript: ['const', 'let', 'var', 'function', 'return', 'if', 'else', 'for', 'while', 'class', 'import', 'export', 'default', 'async', 'await', 'try', 'catch'],
    typescript: ['const', 'let', 'var', 'function', 'return', 'if', 'else', 'for', 'while', 'class', 'import', 'export', 'default', 'async', 'await', 'try', 'catch', 'interface', 'type', 'enum'],
    python: ['def', 'class', 'import', 'from', 'return', 'if', 'else', 'elif', 'for', 'while', 'try', 'except', 'with', 'as', 'lambda', 'True', 'False', 'None'],
  };

  let highlighted = code
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');

  // 高亮字符串
  highlighted = highlighted.replace(/(["'`])(?:(?!\1)[^\\]|\\.)*\1/g, '<span class="text-green-400">$&</span>');

  // 高亮注释
  highlighted = highlighted.replace(/(\/\/.*$|\/\*[\s\S]*?\*\/|#.*$)/gm, '<span class="text-gray-500">$&</span>');

  // 高亮关键字
  const langKeywords = keywords[language] || keywords.javascript;
  langKeywords.forEach(kw => {
    const regex = new RegExp(`\\b(${kw})\\b`, 'g');
    highlighted = highlighted.replace(regex, '<span class="text-purple-400">$1</span>');
  });

  // 高亮数字
  highlighted = highlighted.replace(/\b(\d+)\b/g, '<span class="text-orange-400">$1</span>');

  return highlighted;
}
