import { DiffChange, DiffResult } from '../types';
import { Change, diffLines } from 'diff';
import JSZip from 'jszip';
import { saveAs } from 'file-saver';
import html2canvas from 'html2canvas';

// 计算文件差异
export function calculateDiff(oldContent: string, newContent: string, filename: string): DiffResult {
  const changes = diffLines(oldContent, newContent);
  const diffChanges: DiffChange[] = [];
  let lineNumber = 1;
  let additions = 0;
  let deletions = 0;

  changes.forEach((change: Change) => {
    const lines = change.value.split('\n').filter(l => l !== '' || change.value === '\n');

    lines.forEach(line => {
      if (change.added) {
        diffChanges.push({type: 'add', lineNumber, content: line});
        additions++;
      } else if (change.removed) {
        diffChanges.push({type: 'remove', lineNumber, content: line});
        deletions++;
      } else {
        diffChanges.push({type: 'unchanged', lineNumber, content: line});
      }
      lineNumber++;
    });
  });

  return {
    filename,
    oldContent,
    newContent,
    additions,
    deletions,
    changes: diffChanges
  };
}

// 导出为 ZIP 文件
export async function exportAsZip(
  files: { name: string; content: string }[],
  filename: string = 'project'
): Promise<void> {
  try {
    const zip = new JSZip();

    // 添加文件到ZIP
    files.forEach(file => {
      if (file.name && file.content) {
        zip.file(file.name, file.content);
      }
    });

    // 添加项目说明文件
    const readmeContent = `# ${filename}

Generated by AiCoder

## Files
${files.map(f => `- ${f.name}`).join('\n')}

---
Generated at: ${new Date().toLocaleString()}
`;
    zip.file('README.md', readmeContent);

    // 生成ZIP文件
    const blob = await zip.generateAsync({
      type: 'blob',
      compression: 'DEFLATE',
      compressionOptions: {level: 6}
    });

    // 下载文件
    saveAs(blob, `${filename}.zip`);
  } catch (error) {
    console.error('ZIP导出失败:', error);
    throw new Error('ZIP导出失败，请稍后重试');
  }
}

// 导出为 Markdown 文件
export function exportAsMarkdown(
  content: string,
  title: string = '代码生成结果'
): void {
  try {
    const mdContent = `# ${title}\n\n> 导出时间: ${new Date().toLocaleString()}\n\n${content}\n`;
    const blob = new Blob([mdContent], {type: 'text/markdown;charset=utf-8'});
    saveAs(blob, `${title}.md`);
  } catch (error) {
    console.error('Markdown导出失败:', error);
    throw new Error('Markdown导出失败，请稍后重试');
  }
}

// 导出为图片（对话长图 - 截取整个滚动区域）
export async function exportConversationImage(
  element: HTMLElement,
  filename: string = 'conversation'
): Promise<void> {
  try {
    // 获取元素的完整高度（包括滚动内容）
    const scrollHeight = element.scrollHeight;
    const clientHeight = element.clientHeight;
    const actualHeight = Math.max(scrollHeight, clientHeight);

    // 创建临时容器用于截图
    const container = document.createElement('div');
    container.style.position = 'absolute';
    container.style.left = '-9999px';
    container.style.top = '0';
    container.style.width = element.offsetWidth + 'px';
    container.style.height = actualHeight + 'px';
    container.style.backgroundColor = '#111827'; // 对应 bg-gray-900
    document.body.appendChild(container);

    // 克隆元素
    const clone = element.cloneNode(true) as HTMLElement;
    clone.style.overflow = 'visible';
    clone.style.height = 'auto';
    container.appendChild(clone);

    // 等待DOM更新
    await new Promise(resolve => setTimeout(resolve, 200));

    // 使用html2canvas截图 - 截取完整高度
    const canvas = await html2canvas(clone, {
      backgroundColor: '#111827',
      scale: 2, // 提高清晰度
      useCORS: true,
      logging: false,
      width: element.offsetWidth,
      height: actualHeight,
      scrollY: 0,
      scrollX: 0,
      windowWidth: element.offsetWidth,
      windowHeight: actualHeight
    });

    // 移除临时容器
    document.body.removeChild(container);

    // 转换为图片并下载
    canvas.toBlob((blob) => {
      if (blob) {
        saveAs(blob, `${filename}.png`);
      }
    }, 'image/png');
  } catch (error) {
    console.error('图片导出失败:', error);
    throw new Error('图片导出失败，请稍后重试');
  }
}

// 复制到剪贴板
export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    // 降级方案
    const textarea = document.createElement('textarea');
    textarea.value = text;
    textarea.style.position = 'fixed';
    textarea.style.opacity = '0';
    document.body.appendChild(textarea);
    textarea.select();
    const success = document.execCommand('copy');
    document.body.removeChild(textarea);
    return success;
  }
}